name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show env
        run: env

      - name: Prepare environment
        run: |
          pip install -U pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Run tests
        run: pytest

      - name: Build documentation
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch --all
          git worktree add docs gh-pages
          cd docs
          sphinx-build -b html ../sphinx .
          git add .
          git commit -m "Sphinx build from Action ${GITHUB_SHA}"
          git push origin gh-pages

#      - name: Build wheel
#        run: python -m build -w
#      - name: Upload wheel artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: da_datafix
#          path: dist/*.whl